<?php

use Livewire\Volt\Component;

new class extends Component {
    public string $outItemId;
    public string $inItemId;
    public string $title;
    public int $initialDuration;

    public function mount($outItemId, $inItemId, $title = 'Traffic', $initialDuration = 3600)
    {
        $this->outItemId = $outItemId;
        $this->inItemId = $inItemId;
        $this->title = $title;
        $this->initialDuration = $initialDuration;
    }
};

?>
<div x-data="trafficChart(@js($outItemId), @js($inItemId), @js($title), @js($initialDuration))"
     x-init="chartContainerId = $id('traffic-chart'); init(chartContainerId); return () => destroy()"
     class="relative">

    <!-- Duration Selector -->
    <div class="flex items-center gap-2 mb-2">
        <span class="text-sm font-medium">مدت زمان:</span>
        <select x-model="duration" class="select select-bordered select-sm">
            <option value="1800">30 دقیقه</option>
            <option value="3600">1 ساعت</option>
            <option value="7200">2 ساعت</option>
            <option value="14400">4 ساعت</option>
            <option value="21600">6 ساعت</option>
            <option value="43200">12 ساعت</option>
            <option value="86400">24 ساعت</option>
        </select>
    </div>

    <!-- Chart Container (ID generated by Alpine) -->
    <div :id="chartContainerId" class="relative"></div>

    <!-- Loading Overlay -->
    <div x-show="loading"
         x-cloak
         class="absolute inset-0 flex items-center justify-center bg-base-100/50 z-10 rounded-lg">
        <span class="loading loading-spinner loading-lg text-primary"></span>
    </div>

    <style>
        [x-cloak] { display: none !important; }
    </style>
</div>

<script>
function trafficChart(outItemId, inItemId, chartTitle, initialDuration) {
    return {
        outItemId: outItemId,
        inItemId: inItemId,
        chartTitle: chartTitle,
        duration: initialDuration,
        loading: false,
        chart: null,
        intervalId: null,
        containerId: null, // Will be set by x-init

        init(containerId) {
            this.containerId = containerId;
            this.$nextTick(() => {
                this.initChart();
                // Only load data if chart was successfully created
                if (this.chart) {
                    this.loadData(true);
                    this.intervalId = setInterval(() => this.loadData(false), 10000);
                } else {
                    console.error('Failed to initialize chart for', this.containerId);
                }
            });
            this.$watch('duration', () => this.loadData(true));
        },

        initChart() {
            Highcharts.setOptions({
                time: { timezone: 'Asia/Tehran' }
            });
            try {
                this.chart = Highcharts.chart(this.containerId, {
                    chart: {
                        type: 'spline',
                        backgroundColor: 'transparent',
                        animation: Highcharts.svg,
                    },
                    title: {
                        text: this.chartTitle,
                        style: { color: "var(--color-primary)" }
                    },
                    xAxis: { type: 'datetime' },
                    yAxis: { title: { text: 'Mbps' } },
                    tooltip: { valueSuffix: ' Mbps' },
                    series: [{
                        name: 'Outgoing',
                        data: [],
                        color: "var(--color-warning)"
                    }, {
                        name: 'Incoming',
                        data: [],
                        color: "var(--color-primary)"
                    }]
                });
            } catch (e) {
                console.error('Highcharts error:', e);
                this.chart = null;
            }
        },

        async loadData(showLoading = false) {
            if (!this.chart) {
                console.warn('Chart not ready, skipping data load');
                return;
            }
            if (showLoading) this.loading = true;
            try {
                const url = `/api/zabbix/traffic?out_item_id=${this.outItemId}&in_item_id=${this.inItemId}&duration=${this.duration}`;
                const res = await fetch(url);
                const data = await res.json();
                this.chart.series[0].setData(data.out, false);
                this.chart.series[1].setData(data.in, false);
                this.chart.redraw();
            } catch(e) {
                console.error('Error fetching traffic:', e);
            } finally {
                if (showLoading) this.loading = false;
            }
        },

        destroy() {
            if (this.intervalId) clearInterval(this.intervalId);
            if (this.chart) this.chart.destroy();
        }
    };
}
</script>