<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Middleware\TrustHosts;
use Illuminate\Http\Middleware\TrustProxies;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Exception\SuspiciousOperationException;
use Tests\TestCase;

/**
 * Issue #855: TRUSTED_PROXIES defaulted to '*', which
 * Illuminate\Http\Middleware\TrustProxies turns into
 * setTrustedProxies(['0.0.0.0/0', '::/0'], …) — every address on the internet
 * became a trusted proxy, so a client-supplied X-Forwarded-Host / -Proto /
 * -Prefix became the root of every generated absolute URL.
 *
 * The first two tests go through the REAL middleware stack (a real HTTP
 * request), because that is the only path on which bootstrap/app.php's
 * `at:` value is in play. Driving TrustProxies::at([...]) by hand would assert
 * framework behaviour, not this application's configuration — such a test
 * passes before and after the fix and therefore proves nothing.
 *
 * TrustProxies is driven through TrustProxies::at([...]) + flushState()
 * rather than by mutating .env: bootstrap/app.php reads env() once at boot,
 * and a cached config freezes that value (LoadEnvironmentVariables returns
 * early), so neither an in-test env change nor an edit to .env alone would
 * take effect.
 */
class TrustedProxyHeadersTest extends TestCase
{
    use RefreshDatabase;

    protected function tearDown(): void
    {
        TrustProxies::flushState();
        TrustHosts::flushState();

        // Request::setTrustedHosts() writes Symfony's *static* trusted-host
        // list, which survives the test and makes a later request to any host
        // outside the allowlist throw. Reset it, or the two allowlist tests
        // order-dependently poison every other request in the suite.
        Request::setTrustedHosts([]);

        parent::tearDown();
    }

    /**
     * The forwarded headers an attacker would send. REMOTE_ADDR is a direct
     * client — there is no proxy in the path of the shipped deployment.
     */
    private const array SPOOFED_HEADERS = [
        'X-Forwarded-Host' => 'attacker.example.net',
        'X-Forwarded-Proto' => 'http',
        'X-Forwarded-Port' => '99999',
        'X-Forwarded-Prefix' => '/evil',
    ];

    /**
     * The application must not adopt a client-supplied host by default.
     *
     * Before the fix this fails: with `at: '*'` the real Host header loses and
     * root() becomes http://attacker.example.net:99999/evil.
     */
    public function test_forwarded_headers_do_not_become_the_url_root_by_default(): void
    {
        $this->get('/up', self::SPOOFED_HEADERS + [
            'REMOTE_ADDR' => '198.51.100.10',
        ]);

        $root = request()->root();

        $this->assertStringNotContainsString(
            'attacker.example.net',
            $root,
            'a client-supplied X-Forwarded-Host must not become the request root'
        );
        $this->assertStringNotContainsString(
            '/evil',
            $root,
            'a client-supplied X-Forwarded-Prefix must not become the request root'
        );
        $this->assertStringNotContainsString(
            '99999',
            $root,
            'a client-supplied X-Forwarded-Port must not become the request root'
        );
    }

    /**
     * An absolute URL generated by the app must keep the real host.
     *
     * This is the actual impact: route() and asset() build on request root, so
     * a poisoned root is persisted into notification rows and returned in
     * paginator `links`.
     */
    public function test_generated_absolute_urls_are_not_spoofed(): void
    {
        $this->get('/up', self::SPOOFED_HEADERS + [
            'REMOTE_ADDR' => '198.51.100.10',
        ]);

        $this->assertStringNotContainsString('attacker.example.net', url()->to('/units'));
        $this->assertStringNotContainsString('attacker.example.net', url()->asset('js/app.js'));
    }

    /**
     * The deployed proxy list still works: pinning TRUSTED_PROXIES makes the
     * forwarded headers honoured, so a genuinely proxied deployment keeps its
     * HTTPS detection and URL root.
     */
    public function test_a_pinned_proxy_range_still_honours_forwarded_headers(): void
    {
        TrustProxies::at(['198.51.100.0/24']);

        $request = Request::create('https://dashboard.example.ir/units', 'GET', [], [], [], [
            'REMOTE_ADDR' => '198.51.100.10',
            'HTTP_HOST' => 'dashboard.example.ir',
            'HTTP_X_FORWARDED_HOST' => 'dashboard.example.ir',
            'HTTP_X_FORWARDED_PROTO' => 'https',
        ]);

        app(TrustProxies::class)->handle($request, fn ($r) => $r);

        $this->assertSame(
            'https://dashboard.example.ir',
            rtrim($request->root(), '/'),
            'a pinned proxy must still drive HTTPS detection and the URL root'
        );
    }

    // ==================== trustHosts is the backstop that fails closed ====================

    /**
     * This is the piece that makes a bad TRUSTED_PROXIES fail closed: an
     * out-of-allowlist host throws instead of being silently adopted.
     *
     * Driven through Request::setTrustedHosts() — the exact call
     * TrustHosts::handle() makes — because TrustHosts is inert under
     * `runningUnitTests()` / env=local (shouldSpecifyTrustedHosts()), so
     * going through the middleware would assert nothing here.
     */
    public function test_trusted_host_allowlist_rejects_a_foreign_host(): void
    {
        Request::setTrustedHosts(['^dashboard\.example\.ir$']);

        $this->expectException(SuspiciousOperationException::class);

        Request::create('https://attacker.example.net/units', 'GET', [], [], [], [
            'REMOTE_ADDR' => '198.51.100.10',
            'HTTP_HOST' => 'attacker.example.net',
        ])->getHost();
    }

    public function test_trusted_host_allowlist_admits_the_real_host(): void
    {
        Request::setTrustedHosts(['^dashboard\.example\.ir$']);

        $request = Request::create('https://dashboard.example.ir/units', 'GET', [], [], [], [
            'REMOTE_ADDR' => '198.51.100.10',
            'HTTP_HOST' => 'dashboard.example.ir',
        ]);

        $this->assertSame('dashboard.example.ir', $request->getHost());
    }
}
